apiVersion: apps/v1
kind: Deployment
metadata:
  name: voicevox
  labels:
    app: voicevox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voicevox
  template:
    metadata:
      labels:
        app: voicevox
    spec:
      dnsConfig:
        searches:
          - svc.cluster.local
          - cluster.local
        options:
          - name: single-request-reopen
          - name: use-vc
          - name: ndots
            value: "2"
      containers:
        - name: engine
          image: voicevox/voicevox_engine:cpu-latest
          ports:
            - containerPort: 50021
