apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      dnsConfig:
        searches:
          - svc.cluster.local
          - cluster.local
        options:
          - name: single-request-reopen
          - name: use-vc
          - name: ndots
            value: "2"
      containers:
      - name: httpbin
        image: kennethreitz/httpbin:latest
        resources:
          requests:
            cpu: "10m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 80