apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  namespace: mstdn-soine-site
spec:
  template:
    spec:
      containers:
        - name: db-migrate
          image: tootsuite/mastodon:v4.3.11
          # command: ["bash", "-c", "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails db:migrate"]
          command: ["bash", "-c", "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails runner /utils/rename.rb"]
          envFrom:
            - configMapRef:
                name: env
          volumeMounts:
            - mountPath: /utils
              readOnly: true
              name: mstdn-utils
      volumes:
        - name: mstdn-utils
          configMap:
            name: mstdn-utils
            items:
              - key: rename.rb
                path: rename.rb
      restartPolicy: OnFailure
