apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2025-10-31T22:53:41Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    application: spilo
    cluster-name: za-pg-16
    team: acid
  name: pgdata-za-pg-16-1
  namespace: default
  resourceVersion: "93996910"
  uid: da4fafcb-4b2d-4fb7-8acc-245c74a14e9d
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-da4fafcb-4b2d-4fb7-8acc-245c74a14e9d
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  phase: Bound
