apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotinow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spotinow
  template:
    metadata:
      labels:
        app: spotinow
    spec:
      initContainers:
        - name: init-spotify-cache
          image: busybox:1.36
          command:
            - sh
            - -c
            - touch /cache/.spotifycache
          volumeMounts:
            - name: spotify-cache
              mountPath: /cache
      containers:
        - name: spotinow
          image: ghcr.io/ao-ba/spotify_nowplaying:latest
          stdin: true
          tty: true
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: spotify-secrets
          volumeMounts:
            - name: spotify-cache
              mountPath: /app/.spotifycache
              subPath: .spotifycache
      volumes:
        - name: spotify-cache
          persistentVolumeClaim:
            claimName: spotify-cache
