apiVersion: apps/v1
kind: Deployment
metadata:
  name: addchan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addchan
  template:
    metadata:
      labels:
        app: addchan
    spec:
      dnsConfig:
        searches:
          - svc.cluster.local
          - cluster.local
        options:
          - name: single-request-reopen
          - name: use-vc
          - name: ndots
            value: "2"
      containers:
      - name: addchan
        image: ghcr.io/teamecri/addchan:main
        envFrom:
          - configMapRef:
              name: addchan-env
