apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: misskey-y2e-org
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 3000

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: web-deployment
  namespace: misskey-y2e-org
  labels:
    deploy: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      dnsConfig:
        searches:
          - svc.cluster.local
          - cluster.local
        options:
          - name: single-request-reopen
          - name: use-vc
          - name: ndots
            value: "2"
      containers:
        - name: web
          image: misskey/misskey:2025.12.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /misskey/files
              name: misskey-files
            - mountPath: /misskey/.config
              name: misskey-default-conf-file
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
          resources:
            requests:
              memory: "3Gi"
            limits:
              memory: "4Gi"
      volumes:
        - name: misskey-default-conf-file
          configMap:
            name: misskey-default-config
        - name: misskey-files
          persistentVolumeClaim:
            claimName: misskey-files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misskey-files
  namespace: misskey-y2e-org
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
