apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nrt1-headlamp
  namespace: kube-system
spec:
  defaultBackend:
    service:
      name: headlamp
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - nrt1-headlamp
