apiVersion: apps/v1
kind: Deployment
metadata:
  name: pairdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pairdrop
  template:
    metadata:
      labels:
        app: pairdrop
    spec:
      dnsConfig:
        searches:
          - svc.cluster.local
          - cluster.local
        options:
          - name: single-request-reopen
          - name: use-vc
          - name: ndots
            value: "2"
      containers:
      - name: pairdrop
        image: linuxserver/pairdrop
        envFrom:
          - configMapRef:
              name: pairdrop-env
        volumeMounts:
            - name: pairdrop-config
              mountPath: /etc/pairdrop
      volumes:
        - name: pairdrop-config
          configMap:
            name: pairdrop-config
