apiVersion: apps/v1
kind: Deployment
metadata:
  name: yurecollect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yurecollect
  template:
    metadata:
      labels:
        app: yurecollect
    spec:
      automountServiceAccountToken: false
      containers:
        - name: yurecollect
          image: ghcr.io/yude/yurecollect@sha256:23ccec03d0d0acce49200e2a1a3e14ee68295523a7b8c18d036c0852c15168ae 
          args:
            - "wss://unstable.kusaremkn.com/yure/"
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "1280Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
