apiVersion: batch/v1
kind: CronJob
metadata:
  name: redmine-mail-receive
  labels:
    app: redmine
spec:
  schedule: "*/5 * * * *"
  suspend: true
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: redmine
        spec:
          restartPolicy: Never
          initContainers:
            - name: redmine-config-copy
              image: busybox:1.36
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -lc
                - |
                  set -eu
                  cp /config-src/configuration.yml /config-dst/configuration.yml
                  cat > /config-dst/database.yml <<EOF
                  production:
                    adapter: postgresql
                    database: ${REDMINE_DB_DATABASE}
                    host: ${REDMINE_DB_POSTGRES}
                    port: ${REDMINE_DB_PORT:-5432}
                    username: ${REDMINE_DB_USERNAME}
                    password: ${REDMINE_DB_PASSWORD}
                    encoding: utf8
                  EOF
                  chmod 0644 /config-dst/configuration.yml /config-dst/database.yml
              env:
                - name: REDMINE_DB_POSTGRES
                  value: za-pg-16.default.svc.cluster.local
                - name: REDMINE_DB_USERNAME
                  value: redmine
                - name: REDMINE_DB_PASSWORD
                  value: redmine
                - name: REDMINE_DB_DATABASE
                  value: redmine
                - name: REDMINE_DB_PORT
                  value: "5432"
              volumeMounts:
                - name: redmine-config-src
                  mountPath: /config-src/configuration.yml
                  subPath: configuration.yml
                  readOnly: true
                - name: redmine-config-writable
                  mountPath: /config-dst
          containers:
            - name: redmine-mail-receive
              image: redmine:5.1.11-trixie
              imagePullPolicy: Always
              env:
                - name: RAILS_ENV
                  value: production
                - name: REDMINE_DB_POSTGRES
                  value: za-pg-16.default.svc.cluster.local
                - name: REDMINE_DB_USERNAME
                  value: redmine
                - name: REDMINE_DB_PASSWORD
                  value: redmine
                - name: REDMINE_DB_DATABASE
                  value: redmine
                - name: SECRET_KEY_BASE
                  valueFrom:
                    secretKeyRef:
                      name: redmine-secret
                      key: SECRET_KEY_BASE
                - name: IMAP_HOST
                  valueFrom:
                    secretKeyRef:
                      name: redmine-secret
                      key: IMAP_HOST
                      optional: true
                - name: IMAP_PORT
                  valueFrom:
                    secretKeyRef:
                      name: redmine-secret
                      key: IMAP_PORT
                      optional: true
                - name: IMAP_SSL
                  valueFrom:
                    secretKeyRef:
                      name: redmine-secret
                      key: IMAP_SSL
                      optional: true
                - name: IMAP_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: redmine-secret
                      key: IMAP_USERNAME
                      optional: true
                - name: IMAP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: redmine-secret
                      key: IMAP_PASSWORD
                      optional: true
                - name: IMAP_PROJECT
                  valueFrom:
                    secretKeyRef:
                      name: redmine-secret
                      key: IMAP_PROJECT
                      optional: true
              command:
                - /bin/bash
                - -lc
                - |
                  set -eu
                  bundle exec rake redmine:email:receive_imap \
                    RAILS_ENV=production \
                    host="${IMAP_HOST:-}" \
                    port="${IMAP_PORT:-993}" \
                    ssl="${IMAP_SSL:-true}" \
                    username="${IMAP_USERNAME:-}" \
                    password="${IMAP_PASSWORD:-}" \
                    project="${IMAP_PROJECT:-}" \
                    unknown_user=accept \
                    no_permission_check=1
              volumeMounts:
                - name: redmine-config-writable
                  mountPath: /usr/src/redmine/config/configuration.yml
                  subPath: configuration.yml
                - name: redmine-config-writable
                  mountPath: /usr/src/redmine/config/database.yml
                  subPath: database.yml
          volumes:
            - name: redmine-config-src
              configMap:
                name: redmine-config
            - name: redmine-config-writable
              emptyDir: {}
