apiVersion: v1
kind: Service
metadata:
  name: keikenchi-map
  labels:
    app: keikenchi-map
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: keikenchi-map
