apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberchef
spec:
  selector:
    matchLabels:
      app: cyberchef
  replicas: 1
  template:
    metadata:
      labels:
        app: cyberchef
    spec:
      dnsConfig:
        searches:
          - svc.cluster.local
          - cluster.local
        options:
          - name: single-request-reopen
          - name: use-vc
          - name: ndots
            value: "2"
      containers:
      - name: cyberchef
        image: mpepping/cyberchef:latest
        ports:
        - containerPort: 8000