apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: mi-yude-moe
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 3000

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: web-deployment
  namespace: mi-yude-moe
  labels:
    deploy: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - kube-05
      containers:
        - name: web
          image: misskey/misskey:2025.2.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /misskey/files
              name: misskey-files
            - mountPath: /misskey/.config
              name: misskey-default-conf-file
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
      volumes:
        - name: misskey-default-conf-file
          configMap:
            name: misskey-default-config
        - name: misskey-files
          persistentVolumeClaim:
            claimName: misskey-files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misskey-files
  namespace: mi-yude-moe
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
