apiVersion: v1
kind: ConfigMap
metadata:
  name: es-meili-growi-bridge-config
  labels:
    app: es-meili-growi-bridge
data:
  MEILISEARCH_URL: "http://meilisearch.default.svc.cluster.local:7700"
  LISTEN_ADDR: ":9200"
  LOG_LEVEL: "info"
