apiVersion: v1
kind: Service
metadata:
  name: es-meili-growi-bridge
  labels:
    app: es-meili-growi-bridge
spec:
  selector:
    app: es-meili-growi-bridge
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    protocol: TCP
  type: ClusterIP
