apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
  labels:
    app: mongo-express
type: Opaque
stringData:
  ME_CONFIG_BASICAUTH_USERNAME: admin
  ME_CONFIG_BASICAUTH_PASSWORD: ChangeThisPassword
  ME_CONFIG_SITE_COOKIESECRET: ChangeThisCookieSecret
  ME_CONFIG_SITE_SESSIONSECRET: ChangeThisSessionSecret