apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytnotifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ytnotifier
  template:
    metadata:
      labels:
        app: ytnotifier
    spec:
      dnsConfig:
        searches:
          - svc.cluster.local
          - cluster.local
        options:
          - name: single-request-reopen
          - name: use-vc
          - name: ndots
            value: "2"
      containers:
        - name: ytnotifier
          image: ghcr.io/yude/ytnotifier:master
          volumeMounts:
            - name: ytnotifier-data
              mountPath: /app/gokv
            - name: ytnotifier-config
              mountPath: /app/config.toml
              subPath: config.toml
      volumes:
        - name: ytnotifier-data
          persistentVolumeClaim:
            claimName: ytnotifier-data
        - name: ytnotifier-config
          configMap:
            name: ytnotifier-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ytnotifier-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
