apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberchef
spec:
  selector:
    matchLabels:
      app: cyberchef
  replicas: 1
  template:
    metadata:
      labels:
        app: cyberchef
    spec:
      dnsConfig:
        searches:
          - svc.cluster.local
          - cluster.local
        options:
          - name: single-request-reopen
          - name: use-vc
          - name: ndots
            value: "2"
      containers:
      - name: cyberchef
        image: mpepping/cyberchef:latest
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: robots
          mountPath: /usr/share/nginx/html/robots.txt
          subPath: robots.txt
      volumes:
      - name: robots
        configMap:
          name: cyberchef-robots