apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
  namespace: lldap
spec:
  selector:
    matchLabels:
      app: lldap
  template:
    metadata:
      namespace: lldap
      labels:
        app: lldap
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: lldap
          image: docker.io/lldap/lldap:latest-debian-rootless
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          envFrom:
            - configMapRef:
                name: lldap-config
            - secretRef:
                name: crypto
            - secretRef:
                name: admin-credentials
          ports:
            - name: ldap
              containerPort: 3890
            - name: http
              containerPort: 17170
          volumeMounts:
            - name: lldap-data
              mountPath: /data
            - name: lldap-config-file
              mountPath: /data/lldap_config.toml
              subPath: lldap_config.toml
      volumes:
        - name: lldap-data
          persistentVolumeClaim:
            claimName: lldap
        - name: lldap-config-file
          configMap:
            name: lldap-config-file