apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotify
  template:
    metadata:
      labels:
        app: gotify
    spec:
      dnsConfig:
        searches:
          - svc.cluster.local
          - cluster.local
        options:
          - name: single-request-reopen
          - name: use-vc
          - name: ndots
            value: "2"
      containers:
        - name: gotify
          image: ghcr.io/gotify/server
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/gotify/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gotify-pvc