apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  forwarding.server: |
    tun.y2e.org:53 {
        errors
        cache 30
        forward . 192.168.30.100
    }
    tail5b1c5.ts.net:53 {
        errors
        cache 30
        forward . 100.100.100.100
    }
