apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: za-pg-16
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    test: zalando
  preparedDatabases:
    bar: {}
  postgresql:
    version: "16"
  patroni:
    pg_hba:
      - local   all             all                                   trust
      - hostssl all             +zalandos    127.0.0.1/32       pam
      - host    all             all                127.0.0.1/32       md5
      - hostssl all             +zalandos    ::1/128            pam
      - host    all             all                ::1/128            md5
      - local   replication     standby                    trust
      - hostssl replication     standby all                md5
      - hostnossl all           all                all                md5
      - hostssl all             +zalandos    all                pam
      - hostssl all             all                all                md5