apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pvc-gra.yaml
  - pvc-tra.yaml

configMapGenerator:
  - name: gri-gritab
    files:
      - gritab=./gritab

generatorOptions:
  labels:
    app.kubernetes.io/name: gri
    app.kubernetes.io/component: config
