apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gri-gra
  labels:
    app.kubernetes.io/name: gri
    app.kubernetes.io/part-of: gri
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
