apiVersion: v1
kind: Service
metadata:
  name: gri
  labels:
    app.kubernetes.io/name: gri
    app.kubernetes.io/part-of: gri
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gri
  ports:
    - name: http
      port: 9292
      targetPort: http
