apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: echonet
  namespace: vm
spec:
  staticConfigs:
    - targets:
        - 192.168.30.241
  path: /metrics
  scheme: http
  metricRelabelConfigs:
    - action: keep
      sourceLabels: [__name__]
      regex: "echonet_measured"
