apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operator-and-crds.yaml
  - vmagent.yaml
  - vlagent.yaml
  - vector-loki.yaml
  - echonet.scrape.yaml
  - longhorn.scrape.yaml
  - prober.scrape.yaml
