apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: longhorn
  namespace: vm
spec:
  scheme: http
  path: /metrics
  staticConfigs:
    - targets:
      - longhorn-backend.longhorn-system.svc.cluster.local:9500
  metricRelabelConfigs:
    - action: drop
      regex: "go_.*|process_.*|promhttp_.*"
      sourceLabels: [__name__]
