apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: growi-mongodb-secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["mongodb-rs-admin-admin-user"]
    verbs: ["get"]
