apiVersion: v1
kind: ConfigMap
metadata:
  name: growi
  namespace: growi
data:
  # FILE_UPLOAD: "local"
  FILE_UPLOAD: "aws"
  #S3_BUCKET: ""
  #S3_REGION: ""
  #S3_ENDPOINT: ""
  APP_SITE_URL: "https://w.y2e.org"
  ELASTICSEARCH_URI: "http://es-meili-growi-bridge.default.svc.cluster.local:9200/growi"
