apiVersion: v1
kind: ConfigMap
metadata:
  name: growi
  namespace: growi
data:
  FILE_UPLOAD: "local"
  # FILE_UPLOAD: "s3"
  # S3_BUCKET: ""
  # S3_REGION: ""
  # S3_ENDPOINT: ""
  APP_SITE_URL: "https://w.y2e.org"
