apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-vaultwarden-release-0
  namespace: default
  labels:
    app.kubernetes.io/component: vaultwarden
    app.kubernetes.io/instance: vaultwarden-release
    app.kubernetes.io/name: vaultwarden
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn
