apiVersion: v1
kind: ServiceAccount
metadata:
  name: vaultwarden-svc
  namespace: default
  labels:
    app.kubernetes.io/component: vaultwarden
    app.kubernetes.io/instance: vaultwarden-release
    app.kubernetes.io/name: vaultwarden
